Repository qmk/qmk.fm, pull requests merged in 2019-10, with the labels that each got.

#60 Add German translation for main page
  _data/strings.yml
  _i18n/de/changes.md
  _i18n/de/index.md
  _i18n/de/sidebar.md
Labels: hacktoberfest, translation

#73 Fix QMK Toolbox supported bootloaders links
  _i18n/en/toolbox.md
Labels: enhancement

#62 Add Brazilian portuguese for main page
  _data/strings.yml
  _i18n/pt-br/changes.md
  _i18n/pt-br/index.md
  _i18n/pt-br/sidebar.md
Labels: translation

#78 Reverse order of list of changes in changes.md
  _i18n/en/changes.md
Labels: enhancement

#79 Translated 404 page to German
  _i18n/de/404.md
Labels: translation

#70 Added Chinese translation strings
  _data/strings.yml
Labels: translation

#72 Fix broken gitbook link in the front page
  _i18n/en/index.md
Labels: enhancement

#66 French translation
  _data/strings.yml
  _i18n/fr/404.md
  _i18n/fr/coc.md
  _i18n/fr/converter.md
  _i18n/fr/index.md
  _i18n/fr/sidebar.md
  _i18n/fr/support.md
Labels: awaiting changes, translation

#81 Translated the Code of Conduct into German
  _i18n/de/coc.md
Labels: translation

#88 French translation patch
  _i18n/fr/coc.md
  _i18n/fr/sidebar.md
  _i18n/fr/support.md
Labels: translation

#85 Translated some pages into German
  _i18n/de/converter.md
  _i18n/de/flasher.md
  _i18n/de/powered.md
  _i18n/de/support.md
  _i18n/de/toolbox.md
Labels: awaiting review, translation

#86 Modified links in sidebar.md
  _i18n/de/sidebar.md
Labels: enhancement, translation

#77 Add Italian translation for main page
  _data/strings.yml
  _i18n/it/changes.md
  _i18n/it/index.md
  _i18n/it/sidebar.md
Labels: awaiting changes, translation

#82 German translation for powered, support, proton-c and the categories directory
  _i18n/de/categories/core.md
  _i18n/de/categories/keyboards.md
  _i18n/de/categories/split.md
  _i18n/de/changes.md
  _i18n/de/proton-c.md
  _i18n/de/sidebar.md
Labels: hacktoberfest, translation

#74 Malayalam Translation
  _data/strings.yml
  _i18n/ml/changes.md
  _i18n/ml/index.md
  _i18n/ml/sidebar.md
Labels: translation
