Repository qmk/qmk.fm, pull requests merged in 2019-11, with the labels that each got.

#67 Add Spanish translations
  _data/strings.yml
  _i18n/es/404.md
  _i18n/es/changes.md
  _i18n/es/coc.md
  _i18n/es/converter.md
  _i18n/es/flasher.md
  _i18n/es/index.md
  _i18n/es/license.md
  _i18n/es/powered.md
  _i18n/es/proton-c.md
  _i18n/es/sidebar.md
  _i18n/es/support.md
  _i18n/es/toolbox.md
Labels: hacktoberfest, translation

#87 Add Marathi translation for main page
  _data/strings.yml
  _i18n/mr/changes.md
  _i18n/mr/index.md
  _i18n/mr/sidebar.md
Labels: awaiting changes, translation

#76 Add Hindi Translation for main page
  _data/strings.yml
  _i18n/hi/changes.md
  _i18n/hi/index.md
  _i18n/hi/sidebar.md
Labels: awaiting changes, translation

#91 Add 1upkeyboards Proton-C link
  _i18n/de/proton-c.md
  _i18n/en/proton-c.md
  _i18n/es/proton-c.md
Labels: enhancement

#93 Japanese translation: top pages
  _data/strings.yml
  _i18n/ja/index.md
  _i18n/ja/sidebar.md
Labels: translation
